collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.05952381
color:
  saturation: 0.3783272
  brandStrength: 0.7036341
  lightness: 0.5771502
  brandColors:
    - '#FFFFFF'
    - '#212316'
    - '#B7BA9D'
    - '#464F3E'
    - '#728751'
  rhythmicContrast: 0.09609128
layout_spectrum: 0.7067669
name: Manresa
