collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2061404
color:
  saturation: 0.3783272
  brandStrength: 0.4893484
  rhythmicContrast: 0.09609128
  brandColors:
    - '#FFFFFF'
    - '#212316'
    - '#B7BA9D'
    - '#464F3E'
    - '#728751'
  lightness: 0.5771502
layout_spectrum: 1
name: Manresa
